### ISSUE TITLE
Reduce delay between shortcut and activation

### ISSUE THREAD

**Issue by shakeelmohamed** [janraasch/tab-ahead#18] opened 2015-05-04 05:35 UTC
Hey, just curious if it's possible to reduce the delay between typing the shortcut and actually capturing keystrokes.

Almost daily I'll do my shortcut, `cmd + p` and wait up to 2 seconds before the search bar is activated. So this leads to a strange problem where half my search term gets typed somewhere else.

Thanks for this extension btw, I really love it! :)

**Comment by janraasch** [comment] 2015-05-04 07:49
Hi @shakeelmohamed, thank you for your interest. This is a duplicate of #16 I am afraid. Sadly I do not know how to resolve this.

I will close this since it is a duplicate, but #16 is still open so hopefully someone can chime in with a solution.

**Closed by janraasch** 2015-05-04 07:49 UTC
